import React from 'react'
import './mail.css'
const Mail = () => {
  return (
    <div className='mail'>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, possimus quod sed exercitationem dolorem nisi ducimus hic quidem officia impedit aut dignissimos deleniti quibusdam tenetur? Perferendis fugit corrupti sed beatae eum error alias adipisci expedita sint labore possimus dolor ab aliquid veniam libero aliquam repellat doloribus molestiae similique odit, impedit necessitatibus velit. Labore doloremque saepe sed maiores repellendus maxime, recusandae, aliquid laboriosam iste nemo magnam nisi repudiandae suscipit exercitationem eaque dolore officiis commodi hic! Quod, obcaecati commodi accusantium sint dicta aperiam sapiente quis voluptatum. Nisi aspernatur tempora quia eius repellendus! In saepe necessitatibus similique adipisci voluptate delectus corrupti rerum ex id vero exercitationem aut, nisi tenetur. Odio quam vero neque labore consequuntur fugit. Ad rerum ipsum, reprehenderit aut repudiandae, tempora voluptates veniam ab libero sapiente quas. Dolores eius ea nesciunt. Numquam totam eveniet ut a nam odit minus corporis ad ipsam. Beatae accusantium molestias quam. Aspernatur iste totam adipisci tempora omnis voluptatibus quae dicta quo quaerat ipsum nostrum ex dignissimos voluptates esse, amet suscipit voluptas sint tenetur sed in modi! Corporis et incidunt ipsum natus quas ea quia tempore laborum doloribus, quo laudantium voluptatem totam assumenda? Voluptatem minus omnis consectetur commodi quos ducimus deleniti quod autem perspiciatis facere nostrum, non maxime nulla nesciunt. Repudiandae quas adipisci nisi, in minus reiciendis illum fuga molestiae voluptate sapiente amet, aspernatur odit laborum, eaque sit porro consectetur nostrum! Nihil praesentium, repellendus eum facere provident veniam reprehenderit unde placeat rem repellat iusto veritatis ratione velit earum dolore in expedita incidunt vitae exercitationem perferendis nostrum, voluptates pariatur aut? Architecto distinctio suscipit ullam perferendis enim facere, ipsa porro adipisci consequuntur quos atque nemo veritatis placeat iure, quod nam sint similique. Consectetur, qui deserunt? Doloremque delectus obcaecati cum in nihil nobis hic dolorem ipsam accusantium ut eum ipsa, laborum inventore corporis nostrum at quis, incidunt qui facilis numquam quidem beatae! Debitis perferendis optio sequi totam ducimus tenetur quasi, nihil tempora adipisci a quos vero magnam ipsa numquam eum. Quod sit in sed? Ipsum, cumque doloribus culpa ab reprehenderit facere at cum!
      
    </div>
  )
}

export default Mail
