import React from 'react';
import './sales.css';

const Sales = () => {
  return <div className='sales'>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut id possimus, minus cumque voluptatem perspiciatis consectetur perferendis itaque nesciunt quibusdam placeat quasi? Dolorum, nulla eveniet, assumenda, inventore tenetur praesentium laboriosam necessitatibus in ratione sunt temporibus unde aliquid cupiditate animi magni quae? Mollitia soluta, corrupti ad dignissimos voluptates beatae non in aut voluptate consequatur velit nobis qui porro minus molestiae optio vero odit excepturi nostrum, voluptatum corporis facere. Suscipit cumque reprehenderit aliquid et, eos quo excepturi quaerat magni alias, molestias atque commodi, eveniet veritatis distinctio nulla corrupti a accusantium. Dolores labore, nam, inventore animi necessitatibus voluptatem reiciendis molestiae officia laborum, sequi odio minima veniam dolorum? Modi fugiat quis praesentium nobis, nemo error? Dolore debitis, alias vero modi laborum eveniet quisquam quas! Eius at perferendis inventore molestiae odit ducimus eaque possimus excepturi qui nesciunt, et amet culpa vitae maxime dolor incidunt iure cum quod cupiditate eos reprehenderit mollitia tempore. A at, sapiente porro commodi, nam voluptatem, nesciunt esse enim sint illo repudiandae aperiam? Quaerat praesentium ut animi, ratione recusandae nostrum tenetur omnis quis neque. Doloremque omnis sunt autem eum nesciunt quae voluptatum libero iusto laudantium doloribus commodi totam dicta, nam vero assumenda veritatis? Inventore dolor veritatis quidem temporibus facere asperiores earum delectus vero dolorem mollitia quae ex nihil ea impedit eos, provident necessitatibus esse tempora exercitationem dolores fugit ullam. Hic nihil ut veniam officia illum rerum alias veritatis autem maiores optio aperiam incidunt corporis quaerat expedita voluptatum in vero repudiandae, ipsa, iusto reiciendis placeat esse accusamus quae? Vel ipsum officiis voluptates sit maiores aliquid nemo, voluptatem dolorum voluptatum, ab consectetur quia harum amet architecto pariatur cumque, quis dolorem esse libero vero dolores a illum! Labore quis, veritatis placeat amet recusandae sequi maiores numquam quia at possimus veniam laborum reprehenderit nesciunt deleniti eligendi aspernatur, distinctio commodi aut? Temporibus dignissimos voluptatibus consequuntur recusandae est? Ab distinctio vel incidunt rem, ad vero. Optio illo aliquid blanditiis error ea provident maiores ducimus culpa, suscipit sunt cupiditate saepe esse fugit aliquam libero perferendis consequuntur ratione possimus corrupti reprehenderit in officia.
  </div>;
};

export default Sales;
