import React from 'react'
import './manage.css'

const Manage = () => {
  return (
    <div className='manage'>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur cum totam atque illum quia aperiam rem hic delectus ratione! Consequatur eius molestias excepturi aliquid praesentium est soluta, at blanditiis ut quia minus! Esse, nam! Cum atque non magnam asperiores? Sequi fugiat, quia voluptas placeat eveniet ut. Sit molestiae voluptas saepe neque dolor ipsam veniam eaque recusandae quasi, totam delectus culpa et velit esse iusto ut repellat commodi optio unde sed id! Nesciunt pariatur omnis quam corrupti molestias? Ratione error dolore delectus qui! Aspernatur, incidunt? Hic perferendis molestiae tenetur excepturi voluptatum et consequatur inventore? Saepe et quisquam laborum! Praesentium impedit pariatur qui recusandae odit similique quibusdam eum voluptas sed ducimus, officiis minus id non nesciunt optio tempore debitis maiores ullam quaerat voluptatum aliquam! Temporibus quam necessitatibus molestias assumenda commodi cum saepe amet illo repellat. Accusantium neque nesciunt nam. Incidunt, iste amet quas optio quaerat recusandae dolores, aliquid minima delectus voluptatibus soluta rem magni saepe consectetur quasi quos at! Itaque consequatur vero voluptatum alias neque! Cumque libero nulla porro? Totam doloremque, placeat, sunt nihil ratione debitis beatae harum modi natus nulla ut quasi distinctio eaque fuga sed maiores aspernatur atque praesentium amet. Et, magnam pariatur eveniet reiciendis ad facilis porro. Maiores vero voluptatum dicta minus libero tenetur laudantium necessitatibus doloremque excepturi consequatur ea quisquam beatae ratione rerum a perspiciatis quo id, velit nihil commodi praesentium natus inventore officiis! Atque animi dolorem sit voluptas molestiae dolores impedit odio temporibus aspernatur tenetur minima eveniet unde iusto assumenda aperiam, dolorum commodi. Sed, deleniti fuga? Ipsam amet maxime voluptates rem doloribus hic perspiciatis nihil omnis in corporis dicta libero quidem animi, dolorum ducimus vitae. Architecto omnis impedit labore itaque veritatis quasi nam cum iure recusandae placeat eos a provident ad consectetur aperiam accusantium, molestias rerum explicabo ipsam expedita assumenda fuga esse voluptatem laborum. Vitae deleniti ipsam consequatur nesciunt, unde in consequuntur, odio tenetur, laborum possimus tempora velit molestias debitis dolor. Quaerat at iure provident nesciunt mollitia ut quidem eaque ducimus, blanditiis, eveniet officiis ipsam distinctio dignissimos et dolorum nulla!
    </div>
  )
}

export default Manage
