import React from 'react';
import './analytics.css'

const Analytics = () => {
  return <div className='dummyTextAnalytics'>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia quae fuga id eum officiis ipsa expedita optio itaque, laborum dolores praesentium sequi error illo, quas velit tenetur veniam qui! Nobis molestias temporibus at mollitia in provident praesentium est aliquam excepturi sequi quaerat voluptatibus nihil iste illum consequatur, optio assumenda ut natus voluptate reprehenderit cupiditate exercitationem. Repudiandae, iste illo cumque voluptatem quas corporis necessitatibus veniam quidem cum, ad atque amet quaerat odio enim impedit voluptate dicta. Rem blanditiis facere laudantium nemo perspiciatis illum suscipit optio earum provident temporibus sequi quia ad numquam dolor veritatis quis repellat, omnis iste beatae laboriosam quam nostrum, quibusdam saepe! Architecto cupiditate facilis ut hic, ad aliquid quisquam atque nobis eum ipsum sit nulla totam aperiam sequi odit doloribus voluptates, asperiores, animi iure? Praesentium nostrum in impedit voluptates qui omnis dolores provident tempore! Soluta perspiciatis iure nobis doloribus eos, ipsum nulla, molestias reprehenderit nam a officia quod! Non nesciunt neque debitis nostrum corporis sit rerum, delectus animi, fugit veritatis, eligendi suscipit magni amet nihil perferendis sapiente dolores commodi cupiditate. Reprehenderit ea doloribus, reiciendis illo ullam aperiam quaerat tempore quasi iusto doloremque quae provident quis molestias alias? Porro, possimus quaerat? Illum magni expedita earum maxime quidem eum id ad, atque modi obcaecati et cumque eaque sequi consequuntur quae nisi quos voluptas voluptatem aliquam nam, sunt aut quod dicta aspernatur! Reiciendis possimus placeat facere alias hic voluptatem, ad nam totam doloribus eum excepturi odio minus earum impedit quisquam eos nihil neque recusandae exercitationem voluptas, illo id eius voluptatibus repudiandae? Pariatur, officia! Sed, ipsam ipsa eligendi sit magni quisquam labore magnam fugiat est repellat dolorum ratione alias ducimus iusto incidunt tempora ex possimus saepe in ullam. Ipsam, nisi? Eveniet nisi aut nulla quaerat beatae quasi illum id sunt! Laborum ratione eum iure magnam distinctio dolor, consectetur libero autem facere natus ea nesciunt incidunt. Autem quo, obcaecati nesciunt dolorem maxime sint eveniet unde architecto minus voluptas voluptatum consequuntur saepe, itaque nam incidunt hic magni numquam qui. Voluptates et non distinctio iste maiores modi culpa.
  </div>;
};

export default Analytics;
